# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-11-01 06:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AfterSale',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('number', models.IntegerField(verbose_name='编号')),
                ('title', models.CharField(max_length=50, verbose_name='售后标题')),
                ('sale_type', models.CharField(max_length=32, verbose_name='售后类型')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('state', models.CharField(max_length=32, verbose_name='处理状态')),
            ],
        ),
        migrations.CreateModel(
            name='Bespeak',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('number', models.IntegerField(verbose_name='编号')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='预约时间')),
                ('operator', models.CharField(max_length=32, verbose_name='操作人')),
                ('data_time', models.DateField(verbose_name='操作时间')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32, verbose_name='姓名')),
                ('sex', models.CharField(max_length=32, verbose_name='性别')),
                ('post', models.CharField(max_length=32, verbose_name='职务')),
                ('phone', models.IntegerField(verbose_name='手机号')),
                ('email', models.EmailField(max_length=32, verbose_name='邮箱')),
            ],
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('number', models.IntegerField(verbose_name='编号')),
                ('Personal', models.CharField(max_length=32, verbose_name='日志所属人')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='日志日期')),
                ('jou_level', models.CharField(max_length=32, verbose_name='日志等级')),
            ],
        ),
        migrations.CreateModel(
            name='Organ',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32, verbose_name='机构名称')),
                ('address', models.CharField(max_length=50, verbose_name='机构地址')),
                ('organ_type', models.CharField(max_length=32, verbose_name='机构类型')),
                ('phone', models.IntegerField(verbose_name='手机号')),
                ('website', models.CharField(max_length=50, verbose_name='网站')),
                ('level', models.CharField(max_length=32, verbose_name='重要级别')),
                ('grade', models.CharField(max_length=32, verbose_name='单位等级')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journaltaks.Contact')),
            ],
        ),
        migrations.CreateModel(
            name='OrganAfterSale',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('after_sale_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journaltaks.AfterSale')),
                ('organ_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journaltaks.Organ')),
            ],
        ),
        migrations.CreateModel(
            name='ReservationState',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('res_state', models.CharField(max_length=32, verbose_name='预约状态')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('number', models.IntegerField(verbose_name='编号')),
                ('classify', models.CharField(max_length=32, verbose_name='产品分类')),
                ('Task_person', models.CharField(max_length=32, verbose_name='任务人员')),
                ('level', models.CharField(max_length=32, verbose_name='任务级别')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('date_time', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('organ', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='journaltaks.Organ')),
            ],
        ),
        migrations.AddField(
            model_name='journal',
            name='organ',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='journaltaks.Organ'),
        ),
        migrations.AddField(
            model_name='bespeak',
            name='organ',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='journaltaks.Organ'),
        ),
        migrations.AddField(
            model_name='bespeak',
            name='state',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='journaltaks.ReservationState'),
        ),
        migrations.AddField(
            model_name='aftersale',
            name='organ_after_sale',
            field=models.ManyToManyField(through='journaltaks.OrganAfterSale', to='journaltaks.Organ'),
        ),
    ]
