# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-11-08 03:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journaltaks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bespeak',
            name='data_time',
            field=models.DateTimeField(verbose_name='操作时间'),
        ),
    ]
