# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-11-08 08:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journaltaks', '0002_auto_20181108_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='aftersale',
            name='content',
            field=models.TextField(default=1, max_length=5000, verbose_name='售后内容'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bespeak',
            name='content',
            field=models.TextField(default=1, max_length=500, verbose_name='预约内容'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='content',
            field=models.TextField(default=1, max_length=500, verbose_name='任务内容'),
            preserve_default=False,
        ),
    ]
