# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-11-01 06:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journaltaks', '0002_auto_20181101_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.IntegerField(verbose_name='手机号'),
        ),
    ]
