# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-11-02 00:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journaltaks', '0003_auto_20181101_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='content',
            field=models.TextField(default=1, max_length=500, verbose_name='日志内容'),
            preserve_default=False,
        ),
    ]
