# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-11-03 01:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journaltaks', '0004_journal_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='journal',
            old_name='Personal',
            new_name='personal',
        ),
    ]
