# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-11-08 08:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journaltaks', '0004_auto_20181108_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bespeak',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='预约时间'),
        ),
        migrations.AlterField(
            model_name='bespeak',
            name='data_time',
            field=models.DateTimeField(verbose_name='操作时间'),
        ),
    ]
