# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-11-04 11:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journaltaks', '0005_auto_20181103_0952'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='name',
            new_name='content_name',
        ),
    ]
