# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-11-06 13:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userpermission', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='employee_id',
        ),
        migrations.RemoveField(
            model_name='permission',
            name='status',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='role',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userpermission.Role'),
        ),
    ]
