# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-11-07 08:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userpermission', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Essay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('essay_title', models.CharField(max_length=200)),
                ('comment', models.TextField(max_length=300)),
                ('author', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Essay_category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='essay',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userpermission.Essay_category'),
        ),
        migrations.AddField(
            model_name='essay',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userpermission.File'),
        ),
    ]
