# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-10-31 11:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userpermission', '0002_auto_20181031_1948'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job_category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='job',
            name='job_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userpermission.Job_category'),
        ),
    ]
