# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-11-08 06:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpermission', '0003_file_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='file',
        ),
        migrations.AlterField(
            model_name='essay',
            name='file',
            field=models.FileField(default=None, upload_to=''),
        ),
    ]
