# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-10-31 12:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userpermission', '0003_auto_20181031_1955'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='job_category',
        ),
        migrations.DeleteModel(
            name='Job_category',
        ),
    ]
