# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-10-31 12:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userpermission', '0005_auto_20181031_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userpermission.Department'),
        ),
    ]
